# Generated by Django 5.1.3 on 2024-11-26 20:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GARMENTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('garment_image', models.ImageField(upload_to='media/garment_images')),
                ('description', models.CharField(max_length=350)),
                ('size', models.CharField(max_length=30)),
                ('condition', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=80)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('is_available', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='GARMENT_TAGS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
                ('garment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tags', to='clode.garments')),
            ],
        ),
        migrations.CreateModel(
            name='EXCHANGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=45)),
                ('suggested_location', models.CharField(max_length=255)),
                ('match_date', models.DateTimeField(auto_now_add=True)),
                ('garment_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_exchanges', to='clode.garments')),
                ('garment_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_exchanges', to='clode.garments')),
            ],
        ),
        migrations.CreateModel(
            name='USERS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('location', models.CharField(max_length=150)),
                ('profile_picture', models.ImageField(null=True, upload_to='media/profile_pictures/')),
                ('trust_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('user_type', models.CharField(default='usuario', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='USER_PREFERENCES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefered_free_hours', models.CharField(max_length=80)),
                ('prefered_location', models.CharField(max_length=150)),
                ('prefered_size', models.CharField(max_length=30)),
                ('prefered_size_shoes', models.DecimalField(decimal_places=1, max_digits=2)),
                ('prefered_colors', models.CharField(max_length=50, null=True)),
                ('prefered_style', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='user_preferences', to='clode.users')),
            ],
        ),
        migrations.CreateModel(
            name='SCORES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(max_length=250, null=True)),
                ('rating_date', models.DateTimeField(auto_now_add=True)),
                ('exchange', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='clode.exchange')),
                ('rated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='clode.users')),
                ('rater_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='clode.users')),
            ],
        ),
        migrations.AddField(
            model_name='garments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_garments', to='clode.users'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='receiver_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_exchanges', to='clode.users'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='sender_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_exchanges', to='clode.users'),
        ),
    ]
